### ISSUE TITLE
Need a way to adjust legend position

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/dygraphs#142]
`dyLegend` does not seem to allow adjusting legend position to top-left. When a number of series in the chart are going up with time, the legend looks annoying for its position and size, and that it is not transparent.

Is there a way to move the legend to top-left?

**Comment by pshevtsov** [comment]
@renkun-ken It could be done with [CSS](http://rstudio.github.io/dygraphs/gallery-css-styling.html):

```css
.dygraph-legend {
  left: 70px !important;
  background-color: transparent !important;
}
```
