### ISSUE TITLE
Contribution: CSS for better looking legends

### ISSUE THREAD

**Issue by cvmartin** [rstudio/dygraphs#227]
First of all, thanks for making available dygraphs for R; I find it way faster than D3.js for displaying time series (x10, according to my calculations) and think the library should get more love. 

I use dygraphs in many of my personal projects, and with the time I came up with a CSS for the legend of the graphs that, as I see it, make them look dramatically better:

![dygraph_custom_legend](https://user-images.githubusercontent.com/23063299/50373990-281bb700-05e7-11e9-846d-d790a2c87da8.png)

The changes are:
- The legend looks "neater", with a shadowing of the date and block display of the different series.
- The box of the legend translates to the left when hoovered; a nice way to make all the data visible without placing the legend in its own div.
- When using `dyHighlight()`, the highlighted series is signaled in the legend with a discrete gray left border.

Find below the CSS that I use. To me it works fine including it with `dyCSS()` or sourcing it into the shiny app. Also, I find it nicer to use combined with `dyLegend(show = "onmouseover")`

Please note that I am no expert myself in CSS, so probably the code can be improved (I had to use several infamous `!important`). Any suggestion is welcome, and naturally you are free to include this styling in the package if you find it convenient. Cheers.

``` css
.dygraph-legend {
  width: auto !important;
  min-width: 150px;
  color: white;
  background-color: #BABABA !important;
  padding-left:5px;
  border-color:#BABABA;
  border-style:solid;
  border-width:thin;
  transition:0s 4s;
  z-index: 80 !important;
  box-shadow: 2px 2px 5px rgba(0, 0, 0, .3);
  border-radius: 3px;
}

.dygraph-legend:hover{
  transform: translate(-110%);
  transition: 0s;
}

.dygraph-legend > span {
  color: black;
  padding-left:5px;
  padding-right:2px;
  margin-left:-5px;
  background-color: white !important;
  display: block;
}

.dygraph-legend > span:first-child {
  margin-top:2px;
}

.dygraph-legend > span > span{
  display: inline;
}

.highlight {
  border-left: 2px solid #BABABA;
  padding-left:3px !important;
}
```
